# Generated by Django 2.1.2 on 2019-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190911_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(verbose_name='date IN')),
                ('recordChange', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='component',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
