# Generated by Django 2.1.2 on 2019-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190911_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='invrecord',
            name='recordComponentNo',
            field=models.CharField(default='000', max_length=4),
        ),
        migrations.AlterField(
            model_name='component',
            name='componentNo',
            field=models.CharField(max_length=4),
        ),
    ]
