# Generated by Django 2.1.2 on 2019-09-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190911_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invrecord',
            name='recordDate',
            field=models.CharField(max_length=200),
        ),
    ]
