# Generated by Django 2.2 on 2019-09-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190913_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=100)),
                ('finishTime', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=10)),
            ],
        ),
    ]
